## Modularity for directed graphs (digraphs)

directedModularity.py finds communities or modules in directed networks (digraphs) and evaluates their modularity index. The algorithm which optimizes a modularity function and makes continuous bisections until no further improvement of the modularity function is possible, is from the following paper:
<i>Leicht, Elizabeth A., and Mark EJ Newman. "Community structure in directed networks." Physical review letters 100.11 (2008): 118703.</i>

I have also implemented the undirected version in (https://github.com/rentzi/netRewireAnalyze ). The paper for this is the following:
<i>Newman, M. E. (2006). Modularity and community structure in networks. Proceedings of the national academy of sciences, 103(23), 8577-8582.</i>

In [1]:
# Import dependencies
import numpy as np
import directedModularity # custom-made functions

## I tested different binary digraphs with obvious clustering differences between them. The trend of results is correct

In [6]:
DiGraphStrong2Comp = np.array([[0,1,1,0,0,0],[1,0,1,0,0,0],[1,1,0,0,0,0],[1,0,0,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])

(Q, communitiesDict) = directedModularity.getModularityIndex(DiGraphStrong2Comp)

print('the modularity index for the graph is %f'%Q)
print('')

for comm in communitiesDict.keys():
    print('Cluster %d has the following nodes: '%comm)
    print(communitiesDict[comm])
    print('')

the modularity index for the graph is 0.426036

Cluster 1 has the following nodes: 
[0 1 2]

Cluster 2 has the following nodes: 
[3 4 5]



In [7]:
DiGraphWeaker2Comp = np.array([[0,0,0,0,0,0],[1,0,1,0,0,0],[1,1,0,0,0,0],[1,0,0,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])

(Q, communitiesDict) = directedModularity.getModularityIndex(DiGraphWeaker2Comp)

print('the modularity index for the graph with weaker clustering is %f'%Q)
print('')

for comm in communitiesDict.keys():
    print('Cluster %d has the following nodes: '%comm)
    print(communitiesDict[comm])
    print('')

the modularity index for the graph with weaker clustering is 0.396694

Cluster 1 has the following nodes: 
[0 1 2]

Cluster 2 has the following nodes: 
[3 4 5]



In [8]:
DiGraphWeaker2CompDiscon = np.array([[0,0,0,0,0,0],[0,0,1,0,0,0],[0,1,0,0,0,0],[1,0,0,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])

(Q, communitiesDict) = directedModularity.getModularityIndex(DiGraphWeaker2CompDiscon)

print('the modularity index for the graph with weaker and disconnected clusters is %f'%Q)
print('')

for comm in communitiesDict.keys():
    print('Cluster %d has the following nodes: '%comm)
    print(communitiesDict[comm])
    print('')

the modularity index for the graph with weaker and disconnected clusters is 0.345679

Cluster 1 has the following nodes: 
[1 2]

Cluster 2 has the following nodes: 
[0 3 4 5]



In [9]:
DiGraphWeakest = np.array([[0,0,1,0,0,0],[0,0,1,0,0,1],[1,1,0,0,1,0],[1,1,0,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])

(Q, communitiesDict) = directedModularity.getModularityIndex(DiGraphWeakest)

print('the modularity index for the graph with the weakest clustering is %f'%Q)
print('')

for comm in communitiesDict.keys():
    print('Cluster %d has the following nodes: '%comm)
    print(communitiesDict[comm])
    print('')

the modularity index for the graph with the weakest clustering is 0.204082

Cluster 1 has the following nodes: 
[3 4 5]

Cluster 2 has the following nodes: 
[0 1 2]

